/* eslint-disable @next/next/no-sync-scripts */
import React, { useEffect } from "react";
import Script from "next/script";
import Head from 'next/head';
import { useRouter } from 'next/router';

function TradingView() {


  return (
    <>
    <Head>
    <script id="tradeScript" type="text/javascript" src="https://s3.tradingview.com/tv.js" />
    </Head>
    
      <div className="tr-main">
        
        
        <br/>
      
        <div className="tradingview-widget-container">
          <div id="tradingview_b86f7"></div>
          
          <Script id="initScript" type="text/javascript">
            {`
              new TradingView.widget({
                "autosize": true,
                "symbol": "XAUUSD",
                "interval": "H",
                "timezone": "Asia/Tehran",
                "theme": "dark",
                "style": "3",
                "locale": "en",
                "toolbar_bg": "#f1f8f6",
                "enable_publishing": true,
                "withdateranges": true,
                "hide_side_toolbar": false,
                "allow_symbol_change": true,



                "watchlist": [
                  "BINANCE:BTCUSDT",
                  "FX:EURUSD",
                  "FX:GBPUSD",
                  "BINANCE:BTCUSDTPERP",
                  "BINANCE:ETHUSDT",
                  "COINBASE:BTCUSD",
                  "TVC:GOLD",
                  "COINBASE:ETHUSD",
                  "BINANCE:ETHBTC",
                  "BINANCE:LTCUSDT",
                 "TVC:SILVER",
                 
                 "BINANCE:XRPUSDT",
                 "BINANCE:BCHUSDT",
                 "BINANCE:LTCUSDT",
                 "BINANCE:BNBUSDT",
                 "BINANCE:LINKUSDT",
                 "BINANCE:ADAUSDT",
                 "BINANCE:DOTUSDT",
                 "BINANCE:DOGEUSDT",
                 "BINANCE:EOSUSDT",
                  "BINANCE:TRXUSDT",
                  "BINANCE:XLMUSDT",
                  "BINANCE:ATOMUSDT",
                  "BINANCE:XTZUSDT",
                  "BINANCE:IOTAUSDT",
                  "BINANCE:VETUSDT",
                  "BINANCE:UNIUSDT",
                  "BINANCE:AAVEUSDT",
                  "BINANCE:CAKEUSDT",
                  "BINANCE:ALGOUSDT",
                  "BINANCE:FILUSDT",
                  "BINANCE:MKRUSDT",
                  "BINANCE:COMPUSDT",
                  "BINANCE:KSMUSDT",
                  "BINANCE:ENJUSDT",
                  "BINANCE:SUSHIUSDT",
                  "BINANCE:SNXUSDT",
                  "BINANCE:YFIUSDT",
                  "BINANCE:MANAUSDT",
                  "BINANCE:CRVUSDT",
                  "BINANCE:LRCUSDT",
                  "BINANCE:FTTUSDT",
                  "BINANCE:RENUSDT",
                  "BINANCE:MATICUSDT",
                  "BINANCE:CHZUSDT",
                  "BINANCE:SKLUSDT",
                  "BINANCE:SOLUSDT",
                  "BINANCE:BTTUSDT",
                  "BINANCE:GRTUSDT",
                  "BINANCE:ICPUSDT",
                  "BINANCE:FETUSDT",
                  "BINANCE:BANDUSDT",
                  "BINANCE:OGNUSDT",
                  "BINANCE:1INCHUSDT",
                  "BINANCE:DGBUSDT",
                  "BINANCE:XVGUSDT",
                  "BINANCE:STMXUSDT",
                  "BINANCE:CELRUSDT",
                  "BINANCE:DOCKUSDT",
                  "BINANCE:KEYUSDT",
                  "BINANCE:VTHOUSDT",
                  "BINANCE:HOTUSDT",
                  "BINANCE:WINUSDT",
                  "BINANCE:PERLUSDT",
                  "BINANCE:TROYUSDT",
                  "BINANCE:MTHUSDT",
                  "BINANCE:STPTUSDT",
                  "BINANCE:BLZUSDT",
                  "BINANCE:SNMUSDT",
                  "BINANCE:COSUSDT",
                  "BINANCE:GXSUSDT",
                  "BINANCE:ONGUSDT",
                  "BINANCE:FUELUSDT",
                  "BINANCE:ANKRUSDT",
                  "BINANCE:PHBUSDT",
                  "BINANCE:DLTUSDT",
                  "BINANCE:CELOUSDT",
                  "BINANCE:RSRUSDT",
                  "BINANCE:TCTUSDT",
                  "BINANCE:TROYUSDT",
                  "BINANCE:STPTUSDT",
                  "BINANCE:BLZUSDT",
                  "BINANCE:SNMUSDT",
                  "BINANCE:COSUSDT",
                  "BINANCE:GXSUSDT",
                  "BINANCE:ONGUSDT",
                  "BINANCE:FUELUSDT",
                  "BINANCE:ANKRUSDT",
                  "BINANCE:PHBUSDT",
                  "BINANCE:DLTUSDT",
                  "BINANCE:CELOUSDT",
                  "BINANCE:RSRUSDT",
                  "BINANCE:TCTUSDT",
                  "BINANCE:ALICEUSDT",
                  "BINANCE:ICXUSDT",
                  "BINANCE:IOTXUSDT",
                  "BINANCE:LUNAUSDT",
                  "BINANCE:STMXUSDT",
                  "BINANCE:CTKUSDT",
                  "BINANCE:VITEUSDT",
                  "BINANCE:PERLUSDT",
                  "BINANCE:TROYUSDT",
                  "BINANCE:MTHUSDT",
                  "BINANCE:STPTUSDT",
                  "BINANCE:BLZUSDT",
                  "BINANCE:SNMUSDT",
                  "BINANCE:COSUSDT",
                  "BINANCE:GXSUSDT",
                  "BINANCE:ONGUSDT",
                  "BINANCE:FUELUSDT",
                  "BINANCE:ANKRUSDT",
                  "BINANCE:PHBUSDT",
                  "BINANCE:DLTUSDT",
                  "BINANCE:CELOUSDT",
                  "BINANCE:RSRUSDT",
                  "BINANCE:TCTUSDT",
                  "BINANCE:ALICEUSDT",
                  "BINANCE:ICXUSDT",
                  "BINANCE:IOTXUSDT",
                  "BINANCE:LUNAUSDT",
                  "BINANCE:STMXUSDT",
                  "BINANCE:CTKUSDT",
                  "BINANCE:VITEUSDT",
                  "BINANCE:ALPHAUSDT",
                  "BINANCE:FRONTUSDT",
                  "BINANCE:SXPUSDT",
                  "BINANCE:COMPUSDT",
                  "BINANCE:TOMOUSDT",
                  "BINANCE:LINAUSDT",
                  "BINANCE:MASKUSDT",
                  "BINANCE:TROYUSDT",
                  "BINANCE:STPTUSDT",
                  "BINANCE:BLZUSDT",
                  "BINANCE:SNMUSDT",
                  "BINANCE:COSUSDT",
                  "BINANCE:GXSUSDT",
                  "BINANCE:ONGUSDT",
                  "BINANCE:FUELUSDT",
                  "BINANCE:ANKRUSDT",
                  "BINANCE:PHBUSDT",
                  "BINANCE:DLTUSDT",
                  "BINANCE:CELOUSDT",
                  "BINANCE:RSRUSDT",
                  "BINANCE:TCTUSDT",
                  "BINANCE:ALICEUSDT",
                  "BINANCE:ICXUSDT",
                  "BINANCE:IOTXUSDT",
                  "BINANCE:LUNAUSDT",
                  "BINANCE:STMXUSDT",
                  "BINANCE:CTKUSDT",
                  "BINANCE:VITEUSDT",
                  "BINANCE:ALPHAUSDT",
                  "BINANCE:FRONTUSDT",
                  "BINANCE:SXPUSDT",
                  "BINANCE:COMPUSDT",
                  "BINANCE:TOMOUSDT",
                  "BINANCE:LINAUSDT",
                  "BINANCE:MASKUSDT",
                  "BINANCE:XEMUSDT",
                    "BINANCE:XMRUSDT",
                    "BINANCE:XRPBTC",
                    "BINANCE:XTZBTC",
                    "BINANCE:XVGBTC",
                    "BINANCE:YOYOBTC",
                    "BINANCE:WTCUSDT",
                    "BINANCE:XEMBTC",
                    "BINANCE:XEMUSDT",
                    "BINANCE:XMRBTC",
                    "BINANCE:XMRUSDT",
                    "BINANCE:XRPBTC",
                    "BINANCE:XTZBTC",
                    "BINANCE:XVGBTC",
                    "BINANCE:YOYOBTC",
                    "BINANCE:ZECBTC",
                    "BINANCE:ZENBTC",
                    "BINANCE:ZILBTC",
                    "BINANCE:ZRXBTC",
                    "BINANCE:ZENUSDT",
                    "BINANCE:ZILUSDT",
                    "BINANCE:ZRXUSDT",
                    "BINANCE:ADAUSDC",
                    "BINANCE:ADXBTC",
                    "BINANCE:AGIBTC",
                    "BINANCE:AGIETH",
                    "BINANCE:ALGOBTC",
                    "BINANCE:ALGOUSDC",
                    "BINANCE:AMPLBTC",
                    "BINANCE:ARDRBTC",
                    "BINANCE:ARDRUSDT",
                    "BINANCE:ARNBTC",
                    "BINANCE:ARNETH",
                    "BINANCE:ASTBTC",
                    "BINANCE:BATBTC",
                    "BINANCE:BATUSDT",
                    "BINANCE:BCDBTC",
                    "BINANCE:BCHBTC",
                    "BINANCE:BCHSVBTC",
                    "BINANCE:BCHSVUSDT",
                    "BINANCE:BCHUSDC",
                    "BINANCE:BCHUSDT",
                    "BINANCE:BEAMBTC",
                    "BINANCE:BEAMUSDT",
                    "BINANCE:BLZBTC",
                    "BINANCE:BNBBTC",
                    "BINANCE:BNBUSDC",
                    "BINANCE:BQXBTC",
                    "BINANCE:BQXETH",
                    "BINANCE:BRDBTC",
                    "BINANCE:BTTBTC",
                    "BINANCE:BTTUSDC",
                    "BINANCE:CELRBTC",
                    "BINANCE:CELRUSDC",
                    "BINANCE:CHZBTC",
                    "BINANCE:CHZUSDC",
                    "BINANCE:COCOSBTC",
                    "BINANCE:CTXCUSDT",
                    "BINANCE:CVCBTC",
                    "BINANCE:CVCETH",
                    "BINANCE:DATAUSDT",
                    "BINANCE:DAIUSDT",
                    "BINANCE:DASHBTC",
                    "BINANCE:DASHUSDC",
                    "BINANCE:DAUSDT",
                    "BINANCE:DLTBTC",
                    "BINANCE:DOGEBTC",
                    "BINANCE:DOGEBUSD",
                    "BINANCE:DOCKBTC",
                    "BINANCE:DUSKUSDT",
                    "BINANCE:ENGBTC",
                    "BINANCE:ENJBTC",
                    "BINANCE:ENJETH",
                    "BINANCE:EOSBTC",
                    "BINANCE:EOSUSDC",
                    "BINANCE:ERDBTC",
                    "BINANCE:FETBTC",
                    "BINANCE:FETUSDC",
                    "BINANCE:FIROBTC",
                    "BINANCE:FIROUSDT",
                    "BINANCE:FIOBTC",
                    "BINANCE:FTMBTC",
                    "BINANCE:FTMUSDC",
                    "BINANCE:FUNBTC",
                    "BINANCE:FUNDUSDT",
                    "BINANCE:GASBTC",
                    "BINANCE:GASUSDT",
                    "BINANCE:GOBTC",
                    "BINANCE:GOUSDT",
                    "BINANCE:GRSBTC",
                    "BINANCE:GRSUSDT",
                    "BINANCE:GRTBTC",
                    "BINANCE:GRTUSDC",
                    "BINANCE:HARDBTC",
                    "BINANCE:HARDUSDT",
                    "BINANCE:HCBTC",
                    "BINANCE:HCUSDT",
                    "BINANCE:HOTBTC",
                    "BINANCE:HOTUSDC",
                    "BINANCE:IHTBTC",
                    "BINANCE:INRUSDT",
                    "BINANCE:IOTABTC",
                    "BINANCE:IOTABUSD",
                    "BINANCE:IOSTBTC",
                    "BINANCE:IOSTUSDT",
                    "BINANCE:IOTXBTC",
                    "BINANCE:KAVABTC",
                    "BINANCE:KAVAUSDT",
                    "BINANCE:KEYBTC",
                    "BINANCE:KEYUSDC",
                    "BINANCE:KMDBTC",
                    "BINANCE:KMDUSDT",
                    "BINANCE:KNCBTC",
                    "BINANCE:KNCUSDT",
                    "BINANCE:LENDBTC",
                    "BINANCE:LENDBTC",
                    "BINANCE:LENDUSDT",
                    "BINANCE:LENDUSDT",
                    "BINANCE:LRCBTC",
                    "BINANCE:LRCETH",
                    "BINANCE:LRCUSDC",
                    "BINANCE:LRCUSDT",
                    "BINANCE:LRCUSDT",
                    "BINANCE:LSKBTC",
                    "BINANCE:LSKUSDT",
                    "BINANCE:LTCBTC",
                    "BINANCE:LTCUSDC",
                    "BINANCE:LUNABTC",
                    "BINANCE:LTCUSDT",
                    "BINANCE:LUNABTC",
                    "BINANCE:LUNAUSDC",
                    "BINANCE:MANABTC",
                    "BINANCE:MANAETH",
                    "BINANCE:MANAUSDT",
                    "BINANCE:MATICBTC",
                    "BINANCE:MATICUSDC",
                    "BINANCE:MATICUSDT",
                    "BINANCE:MDTUSDT",
                    "BINANCE:MTLBTC",
                    "BINANCE:NEBLBTC",
                    "BINANCE:NEBLUSDT",
                    "BINANCE:NKNBTC",
                    "BINANCE:NKNUSDT",
                    "BINANCE:NPXSUSDT",
                    "BINANCE:NULSUSDT",
                    "BINANCE:OGNBTC",
                    "BINANCE:OGNUSDT",
                    "BINANCE:OMGBTC",
                    "BINANCE:OMGUSDT",
                    "BINANCE:ONEBTC",
                    "BINANCE:ONEUSDT",
                    "BINANCE:ONGUSDT",
                    "BINANCE:ONTBTC",

                  





                  

              
                ],
                "details": true,
                "hotlist": true,
                "calendar": true,
                
                "studies": ["STD;Accumulation_Distribution"],
                "show_popup_button": true,
                "popup_width": "1000",
                "popup_height": "650",
                "container_id": "tradingview_b86f7",
                "alerts": [
                  {
                    "title": "My Alert 1",
                    "condition": "LAST > 100", // Define your alert condition here
                    "once_per_bar": true,
                    "once_per_session": false,
                  },
                  {
                    "title": "My Alert 2",
                    "condition": "LAST < 50", // Define another alert condition here
                    "once_per_bar": false,
                    "once_per_session": true,
                  }
                  // Add more alerts as needed
                ],

                custom_translate_function: (key, options) => {
                    if (key === 'Indicators') {
                        return 'Mahmoud';
                    }
                    return null;
                },


              });
            `}
          </Script>
        </div>
      </div>
    </>
  );
}

export default TradingView;
